# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: youth_read2

on:
  workflow_dispatch:
  # 账号越多文章越多，运行一次消耗的时间也越长，文章和视频不要一块运行，cron自己看着写
  schedule:
     - cron: '0 0-12/4 * * *'
  watch:
    types: started
env:
  TZ: Asia/Shanghai

jobs:
  build:
    env:
      YOUTH_READ21: ${{ secrets.YOUTH_READ21 }}
      YOUTH_READ22: ${{ secrets.YOUTH_READ22 }}
      YOUTH_READ23: ${{ secrets.YOUTH_READ23 }}
      YOUTH_READ24: ${{ secrets.YOUTH_READ24 }}
      YOUTH_READ25: ${{ secrets.YOUTH_READ25 }}
      YOUTH_READ26: ${{ secrets.YOUTH_READ26 }}
      YOUTH_READ27: ${{ secrets.YOUTH_READ27 }}
      YOUTH_READ28: ${{ secrets.YOUTH_READ28 }}

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
                 
      - name: '运行 【中青看点账号21】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ21 }}
      - name: '运行 【中青看点账号22】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ22 }}
      - name: '运行 【中青看点账号23】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ23 }}
      - name: '运行 【中青看点账号24】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ24 }}
      - name: '运行 【中青看点账号25】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ25 }}
      - name: '运行 【中青看点账号26】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ26 }}
      - name: '运行 【中青看点账号27】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ27 }}
      - name: '运行 【中青看点账号28】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ28 }}


