# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: youth_read6

on:
  workflow_dispatch:
  # 账号越多文章越多，运行一次消耗的时间也越长，文章和视频不要一块运行，cron自己看着写
  schedule:
     - cron: '0 8-22/2 * * *'
  watch:
    types: started
env:
  TZ: Asia/Shanghai

jobs:
  build:
    env:
      YOUTH_READ61: ${{ secrets.YOUTH_READ61 }}
      YOUTH_READ62: ${{ secrets.YOUTH_READ62 }}
      YOUTH_READ63: ${{ secrets.YOUTH_READ63 }}
      YOUTH_READ64: ${{ secrets.YOUTH_READ64 }}
      YOUTH_READ65: ${{ secrets.YOUTH_READ65 }}
      YOUTH_READ66: ${{ secrets.YOUTH_READ66 }}
      YOUTH_READ67: ${{ secrets.YOUTH_READ67 }}
      YOUTH_READ68: ${{ secrets.YOUTH_READ68 }}
      YOUTH_READ69: ${{ secrets.YOUTH_READ69 }}

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install

      - name: '运行 【中青看点账号61】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ61 }}
      - name: '运行 【中青看点账号62】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ62 }}
      - name: '运行 【中青看点账号63】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ63 }}
      - name: '运行 【中青看点账号64】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ64 }}
      - name: '运行 【中青看点账号65】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ65 }}
      - name: '运行 【中青看点账号66】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ66 }}
      - name: '运行 【中青看点账号67】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ67 }}
      - name: '运行 【中青看点账号68】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ68 }}
      - name: '运行 【中青看点账号69】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ69 }}


