# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: youth_read3

on:
  workflow_dispatch:
  # 账号越多文章越多，运行一次消耗的时间也越长，文章和视频不要一块运行，cron自己看着写
  schedule:
     - cron: '0 0-12/4 * * *'
  watch:
    types: started
env:
  TZ: Asia/Shanghai

jobs:
  build:
    env:
      YOUTH_READ31: ${{ secrets.YOUTH_READ31 }}
      YOUTH_READ32: ${{ secrets.YOUTH_READ32 }}
      YOUTH_READ33: ${{ secrets.YOUTH_READ33 }}
      YOUTH_READ34: ${{ secrets.YOUTH_READ34 }}
      YOUTH_READ35: ${{ secrets.YOUTH_READ35 }}
      YOUTH_READ36: ${{ secrets.YOUTH_READ36 }}
      YOUTH_READ37: ${{ secrets.YOUTH_READ37 }}
      YOUTH_READ38: ${{ secrets.YOUTH_READ38 }}
      YOUTH_READ39: ${{ secrets.YOUTH_READ39 }}

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install

      - name: '运行 【中青看点账号31】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ31 }}
      - name: '运行 【中青看点账号32】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ32 }}
      - name: '运行 【中青看点账号33】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ33 }}
      - name: '运行 【中青看点账号34】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ34 }}
      - name: '运行 【中青看点账号35】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ35 }}
      - name: '运行 【中青看点账号36】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ36 }}
      - name: '运行 【中青看点账号37】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ37 }}
      - name: '运行 【中青看点账号38】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ38 }}
      - name: '运行 【中青看点账号39】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ39 }}



