# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: youth_read1

on:
  workflow_dispatch:
  # 账号越多文章越多，运行一次消耗的时间也越长，文章和视频不要一块运行，cron自己看着写
  schedule:
     - cron: '30 0-16/2 * * *'
  watch:
    types: started
env:
  TZ: Asia/Shanghai

jobs:
  build:
    env:
      YOUTH_READ11: ${{ secrets.YOUTH_READ11 }}
      YOUTH_READ12: ${{ secrets.YOUTH_READ12 }}
      YOUTH_READ13: ${{ secrets.YOUTH_READ13 }}
      YOUTH_READ14: ${{ secrets.YOUTH_READ14 }}
      YOUTH_READ15: ${{ secrets.YOUTH_READ15 }}
      YOUTH_READ16: ${{ secrets.YOUTH_READ16 }}
      YOUTH_READ17: ${{ secrets.YOUTH_READ17 }}
      YOUTH_READ18: ${{ secrets.YOUTH_READ18 }}
      YOUTH_READ19: ${{ secrets.YOUTH_READ19 }}

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
                 
      - name: '运行 【中青看点账号11】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ11 }}
      - name: '运行 【中青看点账号12】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ12 }}
      - name: '运行 【中青看点账号13】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ13 }}
      - name: '运行 【中青看点账号14】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ14 }}
      - name: '运行 【中青看点账号15】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ15 }}
      - name: '运行 【中青看点账号16】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ16 }}
      - name: '运行 【中青看点账号17】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ17 }}
      - name: '运行 【中青看点账号18】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ18 }}
      - name: '运行 【中青看点账号19】'
        if: env.YOUTH_READ         
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ19 }}


